#!/bin/bash
set -x

cd $(dirname $0)/..

. ./scripts/version.sh

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
REPO=${REPO:-harbor.lenovo.com/base/rancher}
IMAGE_NAME=${IMAGE_NAME:-k3s}

IMAGE=${REPO}/${IMAGE_NAME}:${TAG}
PROXY_OPTS=
[ -z "$http_proxy" ] || PROXY_OPTS="$PROXY_OPTS --build-arg http_proxy=$http_proxy"
[ -z "$https_proxy" ] || PROXY_OPTS="$PROXY_OPTS --build-arg https_proxy=$https_proxy"
[ -z "$no_proxy" ] || PROXY_OPTS="$PROXY_OPTS --build-arg no_proxy=$no_proxy"
docker buildx create --use --name=builder \
  --driver docker-container --driver-opt \
  image=harbor.lenovo.com/base/buildkit:master-http\
   --buildkitd-flags  '--allow-insecure-entitlement security.insecure'
docker buildx build ${PROXY_OPTS} -t ${IMAGE} -f package/Dockerfile . --platform linux/arm64,linux/amd64 --push
./scripts/image_scan.sh ${IMAGE}
echo Built ${IMAGE}
